### ISSUE TITLE
Is is possible to upload video to Youtube?

### ISSUE THREAD

**Issue by sqrtsanta** [drcmda/learnwithjason#3]
First of all, thank you guys, for `react-three-fiber` & content.

Looks like the stream/video isn't available on Twitch anymore, is it possible to upload to Youtube/Vimeo?

Thanks in advance

**Comment by vojtaholik** [comment]
@Flyr1Q Are you looking for this? https://www.youtube.com/watch?v=1rP3nNY2hTo

**Comment by sqrtsanta** [comment]
@vojtaholik OMG, thanks
